language: node_js
node_js:
  - "0.11"
  - "0.10"
matrix:
  allow_failures:
    - node_js: "0.11"
  fast_finish: true
before_install:
  - "npm install -g grunt-cli"
after_script: "npm run test-coveralls"
